#!/usr/bin/env php
<?php

use Jarvis\Vendor\Output\Console;
use Jarvis\Vendor\Application;
use Jarvis\Vendor\Input\ArgvInput;

try {
    require 'autoloader.php';
    $input = new ArgvInput($argv);
    $output = new Console();
    $app = new Application($input, $output);
    $app->run();
    exit(0);
} catch (\Exception $e) {
    (new Console())->error($e->getMessage());
    exit(1);
}